# Generated by Django 3.0.6 on 2020-06-16 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20200616_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
